name: Build and Deploy

on:
  # 毎日24時（日本時間）に実行（UTC基準で15:00）
  schedule:
    - cron: '0 15 * * *'  # UTC 15:00 = 日本時間 24:00

  # main.pyが更新された時にも実行
  push:
    branches: [ main ]
    paths:
      - 'main.py'

  # プルリクエスト時にも実行（任意）
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mecab libmecab-dev mecab-ipadic-utf8

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile \
                    --add-data "assets:assets" \
                    --hidden-import=janome.tokenizer \
                    --hidden-import=wordcloud \
                    main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4  # ここを修正
      with:
        name: wordcloud-app
        path: dist/main
        retention-days: 1
