
name: PythonBuild

on:
  push:
    branches: [ main ]
    paths: 
      - 'main.py'
      - 'assets/**'
  schedule:
    - cron: '0 15 * * *'  # 日本時間 24:00
  workflow_dispatch:       # ★★ 手動実行を追加 ★★

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: x64

      - name: Upgrade build tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Set up build tools
        run: choco install mingw -y

      - name: Prepare custom PyInstaller
        shell: bash
        run: |
          git clone https://github.com/pyinstaller/pyinstaller.git
          cd pyinstaller/bootloader
          python ./waf distclean all
          cd ..
          python -m pip install .
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Windows executable
        shell: cmd
        run: |
          pyinstaller --noupx ^
                      --name wordcloud-windows.exe ^
                      --add-data "assets;assets" ^
                      --hidden-import=janome.tokenizer ^
                      --hidden-import=wordcloud ^
                      main.py
      - name: Copy assets into dist
        shell: cmd
        run: xcopy /E /I /Y assets dist\assets

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: wordcloud-windows
          path: dist/**
          if-no-files-found: error
