name: PythonBuild

on:
  push:
    branches: [ main ]
    paths:
      - 'main.py'
      - 'assets/**'
  schedule:
    - cron: '0 15 * * *'  # 日本時間 24:00
  workflow_dispatch:      # 手動実行を追加

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: x64

      - name: Upgrade pip & install Nuitka
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install nuitka

      - name: Set up build tools
        run: choco install mingw -y

      - name: Install project dependencies
        run: pip install -r requirements.txt

      - name: Build Windows executable with Nuitka
        shell: cmd
        run: |
          REM standalone + onefile でビルド
          python -m nuitka --standalone --onefile ^
                          --output-dir=dist ^
                          --include-data-dir=assets=assets ^
                          --assume-yes-for-downloads ^
                          main.py
          REM exe 名を変更
          move dist\main.exe dist\wordcloud-windows.exe

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: wordcloud-windows
          path: dist/**
          if-no-files-found: error

